language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      r: devel
    - os: linux
      dist: precise
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
      brew_packages: hunspell
      latex: false
    - os: osx
      osx_image: xcode7.3
      latex: false
      disable_homebrew: true

addons:
  apt:
    packages:
      - libpoppler-cpp-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
